mod 'puppetlabs-firewall'
mod 'puppet-nginx'
mod 'trlinkin-noop'
mod 'geoffwilliams-mount_windows_smb'
mod 'puppet-openvpn'
mod 'puppet-letsencrypt'
mod 'puppetlabs-chocolatey'
mod 'puppet-mongodb'
mod 'puppetlabs-openstack'
mod 'puppetlabs-windows'
mod 'denver-netdata', '0.1.7'
mod 'zleslie-pxe', '0.2.0'
mod 'puppetlabs-mysql', '5.4.0'
mod 'puppetlabs-puppetdb', '6.0.2'
mod 'puppetlabs-apt'
mod 'puppet-archive'
mod 'puppetlabs-concat'
mod 'puppet-dhcp'
mod 'puppetlabs-docker'
mod 'stahnma-epel'
mod 'puppetlabs-image_build'
mod 'puppetlabs-inifile'
mod 'puppetlabs-powershell'
mod 'puppetlabs-registry'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-tftp'
mod 'puppetlabs-translate'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-xinetd'
mod 'puppetlabs-openstack',
  :git => 'https://github.com/puppetlabs/puppetlabs-openstack.git',
  :tag => '4.1.0'
mod 'puppet-selinux', '1.5.2'
mod 'puppetlabs-reboot', '2.0.0'
mod 'puppetlabs-ntp', '7.2.0'


