version: '3.6'
services:
  frontend:
    deploy:
      replicas: 2
    ports:
    - "80:80"
    container_name: frontend
    image: <%= @imgfront %>
  backend:
    deploy:
      replicas: 2
    container_name: backend
    ports:
    - "80:80"
    image: <%= @imgback %>
