mod 'puppet-archive',
  :git => 'git@github.com:jorisdejosselin/puppet-archive.git'
mod 'puppetlabs-firewall',
  :git => 'git@github.com:jorisdejosselin/puppetlabs-firewall.git'
mod 'puppet-nginx',
  :git => 'git@github.com:jorisdejosselin/puppet-nginx.git'
mod 'puppetlabs-apt',
  :git => 'git@github.com:jorisdejosselin/puppetlabs-apt.git'
mod 'trlinkin-noop',
  :git => 'git@github.com:jorisdejosselin/trlinkin-noop.git'
mod 'geoffwilliams-mount_windows_smb',
  :git => 'git@github.com:jorisdejosselin/puppet-mount_windows_smb.git'
mod 'puppet-openvpn',
  :git => 'git@github.com:jorisdejosselin/puppet-openvpn.git'
mod 'puppet-letsencrypt',
  :git => 'git@github.com:jorisdejosselin/puppet-letsencrypt.git'
mod 'chocolatey',
#  :git => 'git@github.com:jorisdejosselin/puppetlabs-chocolatey.git'
mod 'puppet-mongodb',
  :git => 'git@github.com:jorisdejosselin/puppet-mongodb.git'
mod 'puppetlabs-openstack',
  :git => 'git@github.com:jorisdejosselin/puppetlabs-openstack.git'
mod 'puppetlabs-windows',
  :git => 'git@github.com:jorisdejosselin/puppetlabs-windows.git'
mod 'denver-netdata',
  :git => 'git@github.com:jorisdejosselin/denver-netdata.git'
