mod 'puppet-archive',
  :git => 'https://github.com/voxpupuli/puppet-archive.git'
mod 'puppetlabs-firewall',
  :git => 'https://github.com/puppetlabs/puppetlabs-firewall.git'
mod 'puppet-nginx',
  :git => 'https://github.com/voxpupuli/puppet-nginx.git'
mod 'puppetlabs-apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git'
mod 'trlinkin-noop',
  :git => 'https://github.com/trlinkin/trlinkin-noop.git'
mod 'geoffwilliams-mount_windows_smb',
  :git => 'https://github.com/GeoffWilliams/puppet-mount_windows_smb.git'
mod 'puppet-openvpn',
  :git => 'https://github.com/voxpupuli/puppet-openvpn.git'
mod 'puppet-letsencrypt',
  :git => 'https://github.com/voxpupuli/puppet-letsencrypt.git'

mod 'chocolatey-chocolatey',
#^This special motherfucker^#

mod 'puppet-mongodb',
  :git => 'https://github.com/voxpupuli/puppet-mongodb.git'
mod 'puppetlabs-openstack',
  :git => 'https://github.com/puppetlabs/puppetlabs-openstack.git'
mod 'puppetlabs-windows',
  :git => 'https://github.com/puppetlabs/puppetlabs-windows.git'
mod 'denver-netdata',
  :git => 'https://github.com/dmcanally/denver-netdata.git'
